/detect_node:
  ros__parameters:
    bottom_x: 596.0
    bottom_y: 328.0
    hue_white_h: 255.0
    hue_white_l: 0.0
    hue_yellow_h: 61.0
    hue_yellow_l: 0.0
    lightness_white_h: 255.0
    lightness_white_l: 119.0
    lightness_yellow_h: 255.0
    lightness_yellow_l: 179.0
    reliability_white_line: 100.0
    reliability_yellow_line: 96.0
    saturation_white_h: 63.0
    saturation_white_l: 0.0
    saturation_yellow_h: 121.0
    saturation_yellow_l: 0.0
    top_x: 574.0
    top_y: 38.0
