/detect_node:
  ros__parameters:
    bottom_x: 640.0
    bottom_y: 360.0
    hue_white_h: 182.0
    hue_white_l: 19.0
    hue_yellow_h: 83.0
    hue_yellow_l: 0.0
    lightness_white_h: 255.0
    lightness_white_l: 230.0
    lightness_yellow_h: 255.0
    lightness_yellow_l: 255.0
    reliability_white_line: 100.0
    reliability_yellow_line: 100.0
    saturation_white_h: 97.0
    saturation_white_l: 21.0
    saturation_yellow_h: 171.0
    saturation_yellow_l: 3.0
    top_x: 640.0
    top_y: 0.0
